### PR TITLE
Add contributing & update maintainers file

### PR DESCRIPTION
**Pull request by Bwko**

### CODE REVIEW

**Comment by strk** [comment]
LGTM, hoping it'll be counted

**Comment by tboerger** [comment]
We have not added this file to this repo so far because it's somehow a special repository. But I don't care if we add it here as well. LGTM

**Comment by Bwko** [comment]
I think that it's a good idea to add these files to a submodule or something like that. It's a pain in the @#$ to update all the repo's :sweat_smile:

**Comment by tboerger** [comment]
> I think that it's a good idea to add these files to a submodule or something like that. It's a pain in the @#$ to update all the repo's 😅

I know what you mean, I have done that multiple times 8)

**Comment by Bwko** [comment]
Multiple times.. damn... :confounded:
Do we still need the maintainers file? Due to the fact that `ignore_maintainers_file = true` is set

**Comment by tboerger** [comment]
> Do we still need the maintainers file? Due to the fact that ignore_maintainers_file = true is set

Yes, it's just not used by LGTM :)

**Pull request merged**
